### ISSUE TITLE
The option to enable sound notifications does not work.

### ISSUE THREAD

**Issue by rubel-22** [zakius/Smart-RSS#104]
The option to enable sound notifications does not work.
https://i111.fastpic.ru/big/2020/0321/fa/8a4ffd7f49d87d90bc84017059d3befa.png

**Comment by zakius** [comment]
Are you on FF with `media.autoplay.enabled` set to `false`? If so it's expected behavior and there is no way around it (if there was this setting would be useless after all)

I'll try contacting them, maybe they'll make an exception for extensions or allow notifications to play sounds too.

If it's not the case for you I'll look into it

**Comment by zakius** [comment]
Okay, I found an issue that prevented sounds from working at all, though the autoplay quirk stays valid

**Comment by zakius** [comment]
The bug I mentioned is fixed in latest version
