### ISSUE TITLE
all feeds dissappeared

### ISSUE THREAD

**Issue by minusf** [zakius/Smart-RSS#110]
ff 75.0, smartRSS 2.15.0

i have just noticed that all my feeds disappeared.

**Comment by minusf** [comment]
2.15.1 made them come back, closing :}

**Comment by zakius** [comment]
As mentioned in the comment on AMO the 2.15.0 package was malformed and failed to load properly, `All feeds`, `Pinned` and `Thrash` weren't available either due to that issue but no data was actually altered, I pulled back 2.15.0 as soon as I read that comment, analyzed the issue and repackaged manually as the code itself was fine and published as 2.15.1

2.15.2 available here is the same code again packaged automatically but using updated zip library so the package is fine once again, sorry for the trouble
