### ISSUE TITLE
Unrecognized feature: 'picture-in-picture'.

### ISSUE THREAD

**Issue by mbiniek** [zakius/Smart-RSS#12]
Under Opera 58.0.3135.79 (Windows) the following warning appears:

> Unrecognized feature: 'picture-in-picture'.
> (anonymous) @ contentView.js:196

Issue appears for those feeds:
[http://blog.jpalardy.com/atom.xml](http://blog.jpalardy.com/atom.xml)
[https://cezarywalenciuk.pl/blog/programing/feed_channel/rss](https://cezarywalenciuk.pl/blog/programing/feed_channel/rss)

**Comment by zakius** [comment]
This happens when iframe (most often Youtube embed) has set Feature Policy (by `allow` attribute) to allow feature not supported by the browser. It doesn't affect behavior of extension in any way, it just whitelists features that may be enabled in given iframe, if some feature is not supported it wouldn't work either way. There's nothing to fix on my side
