### ISSUE TITLE
prevent adding duplicate feed

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#75]
same feed URL can be added more than once

**Comment by zakius** [comment]
I don't think it's the case, but there may be times when you add the same feed with different schema (`http` or `https') or with or without trailing slash

I don't want to modify the URL when saving it since some webservers may not handle it properly, but I'll try to find a way of generating some deterministic unique ID for each source and looking for that. Probably getting rid of schema and trailing slash if present would make it
