### ISSUE TITLE
all feeds lost after FF v68 update

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#79]
SRR v 2.1.1
updating from FF v67.* to 68 caused all feeds to disappear - i verified the problem by exporting feeds in OPML and indeed there are none

downgrading FF restored the feeds

**Comment by atomGit** [comment]
problem is with `privacy.firstparty.isolate` - set to false, reimport feeds, set to true ... see: https://github.com/openstyles/stylus/issues/747

i'm a clean freak though and i don't know if all the feed data is now stored twice?

i'll let the issue open in case you want to address the problem with an update

**Comment by zakius** [comment]
Mozilla breaking things again, how lovely...

Since 68 is spreading already I'm not sure if I'll be able to figure something out in reasonable time and due to lack of access to filesystem I won't be able to provide any kind of local backup. I'll keep it open for few days at least as I investigate if anything can be done

**Comment by atomGit** [comment]
storage for most other of my extensions wasn't affected, so hopefully this won't be a big deal for you - i use uBO, uM, CanvasBlocker, HTTPZ, etc., and all their data and/or settings were preserved - it was just SRR and Stylus that were affected

**Comment by zakius** [comment]
SRR uses IndexedDB because it may store enourmous amounts of data and this way it is able to perform multiple operations on storage at the same time, others probably use Storage interface explicitly exposed for extensions to use, but what exactly breaks is out of my grasp now, I'll try looking at this this week but can't promise I'll find anything (and I believe if you export SMART on 67 and import it on 68 it will work just fine? or am I mistaken?)

**Comment by atomGit** [comment]
i didn't try a SMART export/import, only OPML, i'd bet it would work fine

**Comment by atomGit** [comment]
it's unfortunate that the morons@mozilla pull this bullshit and leave ext. developers out in the cold, over and over again, while failing to come up with a proper, comprehensive API for extensions

this is no longer an issue for me as i managed to solve it, so i'll leave it up to you if you want to close

sorry you had to spend time on this
