### ISSUE TITLE
2.8.0: what is this number?

### ISSUE THREAD

**Issue by gabri25ele** [zakius/Smart-RSS#91]
![sshot-1](https://user-images.githubusercontent.com/33927879/75544905-35bba080-5a25-11ea-8c41-c6cb98cef78e.png)

updated add-on and now i have this number.
I don't understand what it refers to.
My "Icon badge" setting is disabled.

**Comment by zakius** [comment]
It shows number of detected feeds on active website, I'll be looking for alternative methods of announcing them, sorry for the confusion

You can now easily subscribe to found feeds using toolbar item context menu instead of messy PageAction and I'll be adding extended detection for pages that don't announce feed existence

**Comment by gabri25ele** [comment]
yes, ok I understand. 
but could we have an option to not show that number? 😊

**Comment by zakius** [comment]
sure, now I'm exploring other options to indicate that there is something interesting to do on that website
